spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://192.168.137.130/root/spring-cloud-config.git
          search-paths: respo
          username: root
          password: 12345678
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8888


eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka/
