---
spring:
  profiles: peer1
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
---
spring:
  profiles: peer2
  application:
    name: eureka-server
server:
  port: 8762

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/